apiVersion: v1
data:
  htpasswd: dXNlcjE6JDJ5JDA1JGVDTXk0eHVWeDJSempRamRLNGRjWU9uS28wZnZaMndsSGNiV1d0TzFMdFBFRk90WG9kSFMyCnVzZXIyOiQyeSQwNSRSeDZtVmdWUzF4Z3J2aU1RdHhtSUplVG1qZ1dWM0FCM3gubS9PaDlTNWNhVllrSGFjUUlvRwp1c2VyMzokMnkkMDUkN2NCR2dHdy9HZGFoRm9WSGh2OHFZdUVZdERiaWU4NFlYYmZ6YmhGN2ZaRGtkQTV6M1p6VE8KdXNlcjQ6JDJ5JDA1JDc3Y0YxZDVSS2hmWUdWalE5bFVpTU91eG1SWjJJWVRsWFBaY0FlOFU1T0JERUUxRnpWUWw2CnVzZXI1OiQyeSQwNSRPUzExRHovOGQ1dmMuNUxhTXFPSW1lMS9MZlRKT1pDajdDNVV1aElMUnNubE8ucnVMZHVuLgpjcDokMnkkMDUkT1MxMUR6LzhkNXZjLjVMYU1xT0ltZTEvTGZUSk9aQ2o3QzVVdWhJTFJzbmxPLnJ1TGR1bi4K
kind: Secret
metadata:
  creationTimestamp: null
  name: secret-htpasswd-sre
  namespace: openshift-config
